name: Ansible arborescence deployement
on: 
  #push:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo apt-add-repository --yes --update ppa:ansible/ansible
          sudo apt install -y ansible
          sudo install python3-pip


      - name: upload arborescence
        uses: actions/upload-artifact@v4
        with:
          name: ansible 
          path: ansible/ 
          
      - name: upload inventory
        uses: actions/upload-artifact@v4
        with:
          name: ansible.cfg
          path: ansible.cfg
          
      - name: download arbo
        uses: actions/download-artifact@v4
        with:
          path: .
          name: ansible 

      - name: download inventory
        uses: actions/download-artifact@v4
        with:
          path: .
          name: ansible.cfg
      - name : debug1
        run : pwd
          
      - name : debug2
        run : ls -alh

      - name: deplace
        run: |    
          cd ansible/playbooks
          ansible-playbook ./recette-docker.yaml
          ansible-playbook ./recette-opencti.yaml