name: Deploy to prod
on: workflow_dispatch
  
jobs:
  deploy:
    runs-on: self-hosted
    environment:
      name: prod
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: upload opencti-prod
      uses: actions/upload-artifact@v4
      with:
        name: opencti-prod
        path: .

    - name: download inventory
      uses: actions/download-artifact@v4
      with:
        name: opencti-prod
        path: ~/home/ubuntu

    - name: Display directory content
      run : ls -a ~/home/ubuntu

    - name: Execute docker compose 
      run : cd ~/home/ubuntu/opencti-prod && docker-compose up -d


