---
  name: add ssh key
  on: 
    #push:
    workflow_dispatch:
  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Copy SSH key to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 35.181.49.205 # L'adresse IP ou le nom DNS de votre instance EC2
          username: root
          key: ${{ secrets.TF_SSH_KEY }} # Clé privée SSH pour l'authentification
          script: |
            echo "${{ secrets.TF_SSH_KEY }}" >> /root/.ssh/authorized_keys