name: Run Ansible Playbook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Ansible
      run: |
        pip install ansible

    - name: upload folder
      uses: actions/upload-artifact@v4
      with:
        name: projet
        path: .

    - name: download inventory
      uses: actions/download-artifact@v4
      with:
        name: projet
        path: ~/home/ubuntu

    - name: where
      run : pwd

    - name: Run Ansible playbook
      run: |
        
        ansible-playbook -i ansible/etc/hosts ansible/playbooks/./recette-docker.yaml

      # Replace 'playbook.yml' with the name of your Ansible playbook file
