name: Run Ansible Playbook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Ansible
      run: |
        pip install ansible

    - name: upload inventory
      uses: actions/upload-artifact@v4
      with:
        name: ansible.cfg
        path: ./ansible.cfg

    - name: download inventory
      uses: actions/download-artifact@v4
      with:
        path: .
        name: ./ansible.cfg

    - name: Run Ansible playbook
      run: |
        ansible-playbook -i /etc/hosts ./ansible/playbooks/recette-docker.yaml
      # Replace 'playbook.yml' with the name of your Ansible playbook file
